name: Auto Versioning
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          # This tells the robot to work even without a complex setup
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Version in HTML
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          sed -i "s/APP_VERSION/${{ steps.semantic.outputs.new_release_version }}/g" index.html
          
      - name: Commit version change
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html package.json
          git commit -m "chore: bump version to ${{ steps.semantic.outputs.new_release_version }} [skip ci]"
          git push
